### ISSUE TITLE
GDscript tests combined with C# tests

### ISSUE THREAD

**Issue by martinruefenacht** [CodeDarigan/WATSharp#7]
Awesome tool and thank you for enabling some form of testing!

I played with it for an hour and seems to work pretty well, but it seems to not allow a project to contain GDscript tests and C# tests?

Or am I just setting it up wrong?

EDIT:

I just discovered this in the error log on the Godot side:
```
 res://addons/WAT/ui/metadata/editor.gd:20 - Bug, call error: #308906496
 res://addons/WAT/ui/metadata/editor.gd:20 - Bug, call error: #181160448
 res://tests/player.test.gd:1 - Parse Error: Invalid inheritance (unknown class + subclasses).
 modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR
 res://addons/WAT/ui/metadata/editor.gd:20 - Bug, call error: #181165568
```

I am guessing a C# and GDscript combination is not supported?

**Comment by CodeDarigan** [comment]
Not at the moment. It was on a maybe to-do list but I wasn't sure if anyone used mixed-scripts. It shouldn't be too hard to implement too so I should have something running by the end of the week probably.

**Comment by martinruefenacht** [comment]
I think it would be good to have a Godot-wide scripting language support for a testing framework.

I am mostly using it at the moment, because I am not 100% comfortable to C# yet. Also my UI is in GDScript and the backend simulation is in C#.

**Comment by CodeDarigan** [comment]
Resolved by be588f2093bcbecfd17c212659084583597a9c0e

Extend from WATTest when using GDScript Tests. Most things should work (except for The Nested TestSuiteOfSuites)

**Comment by CodeDarigan** [comment]
Seems this is causing some memory leaks somewhere. Not a huge problem just cleaning somestuff up somewhere.

**Comment by martinruefenacht** [comment]
I got a bad call error #80 on line 64 for test_loader.gd. This is with only C# tests at the moment, which worked with the previous version.

**Comment by CodeDarigan** [comment]
Can you comment line 59 and 60 of test loader back in try to run only c# test afterwards and report back ot me?

**Comment by martinruefenacht** [comment]
With lines 59 & 60 in test_loader uncommented it works as expected.

**Comment by CodeDarigan** [comment]
Try them uncommented with a gd test included and see what happens.

**Comment by martinruefenacht** [comment]
Now the test variable is nil and throws null_instance error.

I am using the Introduction Player + player.test.gd, the "extends WAT.Test" says Invalid Inheritance.

**Comment by CodeDarigan** [comment]
I removed the WAT.Test from GDScript because I thought it would cause a problem. However just tested it and doesn't seem to cause any name conflicts. I added it back in b0835e4a4b44042a2e6786cc180ea9ebb0cf55ba so you should avoid the inheritance problem.

**Comment by martinruefenacht** [comment]
<img width="853" alt="Screenshot 2020-05-26 at 12 31 23" src="https://user-images.githubusercontent.com/825164/82896096-42309600-9f4d-11ea-8a10-82d6e850b9b5.png">

For some reason, path == "re".

When I explicit run the C# scripts it works fine. This is with lines 59 & 60 uncommented.

**Comment by martinruefenacht** [comment]
Also for some reason "player.test.gd" is reported twice in the scripts drop down.

**Comment by CodeDarigan** [comment]
Okay for some reason my commits were becoming a mess. Can you download the latest master branch and run tests from there? It should work this time.

**Comment by martinruefenacht** [comment]
Seems to be working now!

**Comment by martinruefenacht** [comment]
Thanks for the quick implementation...

**Comment by CodeDarigan** [comment]
Awesome. No problem!
